# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 13:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MovieRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_1s', to='movies.Movie')),
                ('movie_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_2s', to='movies.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movierelation',
            unique_together=set([('movie_1', 'movie_2')]),
        ),
    ]
