# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20170407_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='comedy', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='is_explored',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
